# Python Codes - Part 6 [Packages]
- The highest hierarchy in Python is a Package or Library that is a group of related classes, functions, variables, and even sub-packages.
- Many companies and universities like Google, Facebook, Stanford, etc, develop and release Python packages on the internet.
- Individuals can also release packages on the internet.
- Using the packages developed by others, speeds up and makes it much more easier to build our own AI systems. We are truly standing on the shoulders of giants!

<img src="images/10/package.png" />

## Working with packages
- The numpy package provides many useful functions to work with lists.
- The numpy equivalent of a list is called an array.
- NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use: [Source](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [ ]:
# Install numpy package if not already installed
# ! pip install numpy

### Import numpy

In [2]:
# This is an example of importing a package and assigning an alias name
import numpy as np

In [3]:
# In subsequent lines of code, we can use the alias name to access classes, functions and attributes (variables) from this package
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [4]:
# This is an example of importing a single class from a package
from numpy import random

In [5]:
random_array = random.randint(0, 10, 5)
print(random_array)

[3 7 9 5 4]


### List to Array
<img src="images/03/ndlist.png" />

In [6]:
# Create a numpy array from a list
count_to_ten = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(count_to_ten)

count_to_ten_array = np.array(count_to_ten)
print(count_to_ten_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Numpy can change a 1D to a 2D array easily by using .reshape(n_rows, n_cols). Each is called one axis
count_to_ten_2d = count_to_ten_array.reshape(5, 2)
print(count_to_ten_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [8]:
# -1 can be used for any axis that we are not sure of
count_to_ten_2d = count_to_ten_array.reshape(5, -1)
print(count_to_ten_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### + operator

In [9]:
# + operation achieves itemwise addition on two numpy arrays (instead of concatenate as in lists)
list_1 = [1, 2, 3, 4, 5]
list_2 = [6, 7, 8, 9, 10]
print('List addition is concatenation: ', list_1 + list_2)

array_1 = np.array(list_1)
array_2 = np.array(list_2)
print('Numpy addition is item wise addition: ', array_1 + array_2)

List addition is concatenation:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Numpy addition is item wise addition:  [ 7  9 11 13 15]


In [10]:
list_1 = [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
list_2 = [[6, 7, 8, 9, 10], [6, 7, 8, 9, 10]]
print('List addition is concatenation: ', list_1 + list_2)

array_1 = np.array(list_1)
array_2 = np.array(list_2)
print('Numpy addition is item wise addition: \n', array_1 + array_2)

List addition is concatenation:  [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [6, 7, 8, 9, 10]]
Numpy addition is item wise addition: 
 [[ 7  9 11 13 15]
 [ 7  9 11 13 15]]


### Accessing individual items and slicing

In [11]:
# Individual items in a numpy array can be accessed similar to lists by using the index or by slicing
print(array_1[0][2])
print(array_1[0][:2])

3
[1 2]


### Matrix multiplication
- Numpy can do very fast matrix multiplication

<img src="images/10/matrix_mul.png" width="500"/>

In [12]:
list_1 = [[1, 2, 3], [4, 5, 6]]
list_2 = [[10, 11], [20, 21], [30, 31]]

np.matmul(list_1, list_2)

array([[140, 146],
       [320, 335]])

## Summary
- Python packages are groups of related classes, functions, variables, and even sub-packages written by other Python programmers.
- Install a Python package from the internet using ```! pip install <package_name>```.
- Import a package by using ```import``` statement.
- Numpy is a versatile Python package that adds much more functionality to list like variables.